### ISSUE TITLE
it will report "java.lang.OutOfMemoryError: Java heap space" when read game record in multithreading.

### ISSUE THREAD

**Issue by hongBry** [seekloud/ESSF#5]
exception like:
```
java.lang.OutOfMemoryError: Java heap space
	at org.seekloud.essf.box.Boxes$SimulatorFrame$.$anonfun$readFromBuffer$8(Boxes.scala:238)
	at org.seekloud.essf.box.Boxes$SimulatorFrame$$$Lambda$33/1023659307.apply(Unknown Source)
	at scala.util.Try$.apply(Try.scala:209)
	at org.seekloud.essf.box.Boxes$SimulatorFrame$.readFromBuffer(Boxes.scala:235)
	at org.seekloud.essf.io.ESSFReader.decodeBox(ESSFReader.scala:67)
	at org.seekloud.essf.io.ESSFReader.get(ESSFReader.scala:40)
	at org.seekloud.essf.io.FrameInputStream.init(FrameInputStream.scala:57)
	at essf.example.RecallTest$.readData(RecallTest.scala:30)
	at essf.example.RecallTest$.$anonfun$main$2(RecallTest.scala:55)
	at essf.example.RecallTest$$$Lambda$8/120960120.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
	at scala.concurrent.Future$$$Lambda$10/1307096070.apply(Unknown Source)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.Future$$Lambda$11/2081303229.apply(Unknown Source)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.Promise$$Lambda$12/1418428263.apply(Unknown Source)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by hongBry** [comment]
the reason of the exception is :
the companion objects "ESSFReader" has maintained a ByteBuffer to read “Box” header,  It can't guarantee thread safety.

I will fix it.
